name: Somnolence
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.9


  
  audioplayers: ^4.1.0
  # table_calendar: ^2.1.0
  camera_web:
  camera:
  
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  http: ^0.13.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/model.tflite
    - assets/labels.txt

dev_dependencies:

  flutter_test:
    sdk: flutter

  lints: ^2.0.0
  test: ^1.21.0
